Repository ember-codemods/tagless-ember-components-codemod, pull requests merged in 2019-11, with the labels that each got.

#19 Add support for running on addons
  lib/index.js
Labels: enhancement

#20 CI: Add "Release" workflow
  .github/workflows/release.yml
Labels: internal

#21 Add dependabot configuration file
  .dependabot/config.yml
Labels: internal

#28 Fix attributeBindings issue
  lib/__tests__/__snapshots__/transform.js.snap
  lib/__tests__/find-properties.js
  lib/transform.js
Labels: bug
