Repository ember-codemods/tagless-ember-components-codemod, pull requests merged in 2020-01, with the labels that each got.

#48 Drop Node 8 support
  .github/workflows/ci.yml
  package.json
Labels: breaking

#43 Extract transforms and utils
  lib/__tests__/find-properties.js
  lib/__tests__/transform.js
  lib/transform.js
  lib/transform/classic.js
  lib/transform/template.js
  lib/utils.js
Labels: internal

#51 Add support for `ariaRole` property
  lib/__tests__/__snapshots__/transform.js.snap
  lib/__tests__/transform.js
  lib/transform/classic.js
  lib/transform/template.js
  lib/utils.js
Labels: enhancement

#50 Add support for passing paths or glob patterns as CLI options
  README.md
  bin/cli.js
  lib/index.js
Labels: enhancement

#53 Fix empty package.json dependencies
  lib/index.js
Labels: bug

#58 Add `this.` prefix to `styleNamespace` property
  lib/__tests__/__snapshots__/transform.js.snap
  lib/transform/template.js
Labels: enhancement
